name: FPGA
on: [push]
jobs:
  fpga:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Tools
        run: sudo apt-get update && sudo apt-get install -y verilator
      - name: Compile and Simulate
        run: verilator --binary -j 0 project.v
