name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python and Sandpiper
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install sandpiper-saas==1.1.0 --no-input
      - name: Install Verilator
        run: sudo apt-get install -y verilator
      - name: Verify Working Directory and Files
        run: |
          pwd  # Print current working directory
          ls -la  # List all files to confirm src/project.tlv exists
      - name: Compile TL-Verilog
        run: |
          # Ensure we're in the correct directory and bypass ToS prompt
          cd /home/runner/work/test123/test123
          echo "y" | sandpiper-saas -i src/project.tlv -o project.v --top my_module --verbose
        working-directory: /home/runner/work/test123/test123
      - name: List Files
        run: ls -la
      - name: Check project.v
        run: cat project.v || echo "No project.v generated"
      - name: Build and Simulate
        run: verilator --binary -j 0 --trace -f testbench.v project.v && ./obj_dir/Vtestbench
