name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python and Sandpiper
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          # Install a custom or patched version of sandpiper-saas from GitHub
          pip3 install git+https://github.com/makerchip/sandpiper.git@disable-tos-prompt --no-input
          # Alternatively, if the above fails, use a local patch
          if [ $? -ne 0 ]; then
            pip3 install sandpiper-saas==1.0.0 --no-input
            echo "Patching sandpiper-saas to skip ToS prompt"
            sed -i 's/if click.confirm/if False  # Disabled ToS prompt for CI/' /home/runner/.local/lib/python3.12/site-packages/sandpiper/__init__.py
          fi
      - name: Install Verilator
        run: sudo apt-get install -y verilator
      - name: Compile TL-Verilog
        run: sandpiper-saas -i project.tlv -o project.v --top my_module --verbose
      - name: List Files
        run: ls -la
      - name: Check project.v
        run: cat project.v || echo "No project.v generated"
      - name: Build and Simulate
        run: verilator --binary -j 0 --trace -f testbench.v project.v && ./obj_dir/Vtestbench
