name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Sandpiper
        run: pip install sandpiper-saas
      - name: Install Verilator
        run: sudo apt-get update && sudo apt-get install -y verilator
      - name: Compile TL-Verilog
        run: sandpiper-saas -i project.tlv -o project.v
      - name: Simulate
        run: verilator --binary -j 0 project.v --trace
      - name: Check Results
        run: ./obj_dir/Vmy_module
