name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python and Sandpiper
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install sandpiper-saas
      - name: Install Verilator
        run: sudo apt-get install -y verilator
      - name: Compile TL-Verilog
        run: sandpiper-saas -i project.tlv -o project.v --top my_module --verbose
      - name: List Files
        run: ls -la
      - name: Build and Simulate
        run: verilator --binary -j 0 --trace project.v && ./obj_dir/Vmy_module
